### ISSUE TITLE
eu.stratosphere.tutorial.task1: input file does not exist

### ISSUE THREAD

**Issue by sgraphics** [stratosphere/bigdataclass.org#1]
Hi,

Running into an issue with FileDataSource. When I specify a folder for input and run the first task (eu.stratosphere.tutorial.task1), the exception is

``` java
Exception in thread "main" eu.stratosphere.nephele.client.JobExecutionException: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot compute input splits for Input Documents: java.io.FileNotFoundException: File file://C:\Users\Silver\AppData\Local\Temp\input does not exist.
```

The folder btw does exist and has 2 files, 1.txt and 2.txt.

I have tried multiple folders, with different permission sets. I also tried to set a file as the input ("... input\1.txt"), and got ...\input\1.txt does not exist.

Running it in Windows 8.1, with Eclipse and M2Eclipse.

Full stack trace:

``` java
13/10/30 13:39:05 ERROR client.JobClient: ERROR: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot compute input splits for Input Documents: java.io.FileNotFoundException: File file://C:\Users\Silver\AppData\Local\Temp\input does not exist.
    at eu.stratosphere.nephele.fs.file.LocalFileSystem.getFileStatus(LocalFileSystem.java:106)
    at eu.stratosphere.pact.generic.io.FileInputFormat.createInputSplits(FileInputFormat.java:323)
    at eu.stratosphere.pact.generic.io.FileInputFormat.createInputSplits(FileInputFormat.java:71)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.computeInputSplits(DataSourceTask.java:326)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:554)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:480)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)

    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:557)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:480)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)

Exception in thread "main" eu.stratosphere.nephele.client.JobExecutionException: eu.stratosphere.nephele.executiongraph.GraphConversionException: Cannot compute input splits for Input Documents: java.io.FileNotFoundException: File file://C:\Users\Silver\AppData\Local\Temp\input does not exist.
    at eu.stratosphere.nephele.fs.file.LocalFileSystem.getFileStatus(LocalFileSystem.java:106)
    at eu.stratosphere.pact.generic.io.FileInputFormat.createInputSplits(FileInputFormat.java:323)
    at eu.stratosphere.pact.generic.io.FileInputFormat.createInputSplits(FileInputFormat.java:71)
    at eu.stratosphere.pact.runtime.task.DataSourceTask.computeInputSplits(DataSourceTask.java:326)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:554)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:480)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)

    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.createVertex(ExecutionGraph.java:557)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.constructExecutionGraph(ExecutionGraph.java:275)
    at eu.stratosphere.nephele.executiongraph.ExecutionGraph.<init>(ExecutionGraph.java:176)
    at eu.stratosphere.nephele.jobmanager.JobManager.submitJob(JobManager.java:480)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at eu.stratosphere.nephele.ipc.RPC$Server.call(RPC.java:417)
    at eu.stratosphere.nephele.ipc.Server$Handler.run(Server.java:946)

    at eu.stratosphere.nephele.client.JobClient.submitJobAndWait(JobClient.java:272)
    at eu.stratosphere.pact.client.LocalExecutor.executePlan(LocalExecutor.java:80)
    at eu.stratosphere.tutorial.util.Util.executePlan(Util.java:169)
    at eu.stratosphere.tutorial.task1.DocumentFrequencyPlan.main(DocumentFrequencyPlan.java:95)

```

**Comment by uce** [comment]
This is a bug in the test setup (we only tested on UNIX-like systems). We have somebody working on this issue in general (see [issue 217](https://github.com/stratosphere/stratosphere/issues/217) of the Stratosphere repository).

The easiest fix is to change some lines in `eu.stratosphere.tutorial.util.Util` of the tutorial. The methods `createTempFile` (line 174), `createTempDir` (180) and `getTempPath` (185) have the prefix `file://` hardcoded.

Please change it to `file:\\`. If you ever test with your own files, make sure to also use `file:\\` as prefix, e.g. `file:\\C:\your\path`.

**Comment by sgraphics** [comment]
Thanks, this worked!
